<template>
  <div>

      <el-card v-for="(patientAttrObj,index) in patient" :key="index">
          <a href="javascript:;" style="display:block;" @click="showDialog(patientAttrObj)">
            {{patientAttrObj.room}}
          </a>
      </el-card>

      <el-dialog
        title="患者详情"
        :visible.sync="dialogVisible"
        width="90%"
        :before-close="handleClose">
        <span>
            <el-table
            :data="tableShowList"
            border
            >

                <el-table-column
                prop="name"
                label="姓名"
                >
                </el-table-column>

                <el-table-column
                prop="pulm"
                label="意识及状态"
                width="100"
                >
                </el-table-column>

                <el-table-column
                prop="bodyTempratrue"
                label="肌力"
                >
                </el-table-column>

                <el-table-column
                prop="breath"
                label="坐位平衡"
                >
                </el-table-column>

                <el-table-column
                prop="date"
                label="感觉功能"
                >
                </el-table-column>

                <el-table-column
                prop="tuyan"
                label="吞咽功能"
                >
                </el-table-column>

                <el-table-column
                prop="pain"
                label="疼痛"
                >
                </el-table-column>


                <el-table-column
                prop="pingfen"
                label="视觉模拟评分(VAS)"
                width="100"
                >
                    
                    <template slot-scope="{row}">
                        <el-input size="mini"></el-input>
                    </template>
                </el-table-column>

                <el-table-column
                prop="zhiti"
                label="肢体肿胀"
                >
                </el-table-column>

                <el-table-column
                prop="zhishu"
                label="ADL(BartheI)指数"
                width="100"
                >
                    
                    <template slot-scope="{row}">
                        <el-input size="mini"></el-input>
                    </template>
                </el-table-column>

                <el-table-column
                prop="piantan"
                label="偏瘫"
                >
                </el-table-column>
                <el-table-column
                prop="fenqi"
                label="Brunnstorm分期（上）"
                width="150"
                >
                    
                    <template slot-scope="{row}">
                        <el-input size="mini"></el-input>
                    </template>
                </el-table-column>
                <el-table-column
                prop="guanjie"
                label="关节活动度"
                >
                </el-table-column>
                <el-table-column
                prop="jizhang"
                label="肌张力"
                >
                </el-table-column>
                <el-table-column
                prop="zhanli"
                label="站立平衡"
                >
                </el-table-column>
                <el-table-column
                prop="fuzhu"
                label="辅助工具"
                >
                </el-table-column>

                <el-table-column
                prop="butai"
                label="步态分析"
                >
                </el-table-column>

                <el-table-column
                prop="buwei"
                label="疼痛部位"
                >
                </el-table-column>

                <el-table-column
                prop="yuyan"
                label="语言功能"
                >
                </el-table-column>

                <el-table-column
                prop="renzhi"
                label="认知心理评价"
                >
                </el-table-column>

                <el-table-column
                prop="miaoshu"
                label="心肺功能（肺功能表述）"
                width="150"
                >
                    
                    <template slot-scope="{row}">
                        <el-input size="mini"></el-input>
                    </template>
                </el-table-column>
                <el-table-column
                prop="shou"
                label="Brunnstorm分期（手）"
                width="150"
                >
                    <template slot-scope="{row}">
                        <el-input size="mini"></el-input>
                    </template>
                </el-table-column>

                <el-table-column
                prop="xia"
                label="Brunnstorm分期（下）"
                width="150"
                >
                    
                    <template slot-scope="{row}">
                        <el-input size="mini"></el-input>
                    </template>
                </el-table-column>

            </el-table>

        </span>
        <span slot="footer" class="dialog-footer">
            <el-button @click="dialogVisible = false">取 消</el-button>
            <el-button type="primary" @click="dialogVisible = false">确 定</el-button>
        </span>
      </el-dialog>

      <el-pagination
        background
        layout="prev, pager, next"
        :total="100"
        style="float:right;marginTop:20px;"
        >
      </el-pagination>
  </div>
</template>

<script>
export default {
    data(){
        return {
            dialogVisible:false,
            patient:[
                {
                    room:`101号病房患者 /\t (点击查看患者详细信息)`,
                    dataList:[
                        {
                            name:'邢佳辉',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'边驰',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'李本旭',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'王锦涛',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },
                {
                    room:'201号病房患者',
                    dataList:[
                        {
                            name:'朱小强',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'蔡秋雨',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'刘国强',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'王楠',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },
                {
                    room:'301号病房患者',
                    dataList:[
                        {
                            name:'凌宏健',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'吴羊',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'张菡一',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'王淼',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },
                {
                    room:'401号病房患者',
                    dataList:[
                        {
                            name:'梁秋伯',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'爱小林',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'李涛',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'郭振明',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },
                {
                    room:'501号病房患者',
                    dataList:[
                        {
                            name:'高达辉',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'马赛',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'牛心哲',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'杨亮',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },
                {
                    room:'601号病房患者',
                    dataList:[
                        {
                            name:'谭利花',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'王鑫其',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'刘雨珩',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'朱一冰',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },
                {
                    room:'701号病房患者',
                    dataList:[
                        {
                            name:'陈瑞金',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'马宇斌',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'翟至豪',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'王秀娟',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },
                {
                    room:'801号病房患者',
                    dataList:[
                        {
                            name:'王志勇',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'可疑'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'II'
                            ,piantan:'左侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'手臂'
                            ,yuyan:'理解异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'理想',
                            pulm:'清晰',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'无肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'III'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'臀部'
                            ,yuyan:'语言异常'
                            ,renzhi:'睡眠异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'卢龙',
                            pulm:'模糊',
                            bodyTempratrue:'异常',
                            breath:'I',
                            date:'异常',
                            tuyan:'异常'
                            ,pain:'无疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'右侧'
                            ,fenqi:''
                            ,guanjie:'正常'
                            ,jizhang:'正常'
                            ,zhanli:'I'
                            ,fuzhu:'需要支架'
                            ,butai:'异常步态'
                            ,buwei:'小腿'
                            ,yuyan:'理解异常'
                            ,renzhi:'饭量异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                        {
                            name:'杨帆',
                            pulm:'清晰',
                            bodyTempratrue:'正常',
                            breath:'II',
                            date:'异常',
                            tuyan:'正常'
                            ,pain:'疼痛'
                            ,pingfen:''
                            ,zhiti:'肿胀'
                            ,zhishu:''
                            ,xinfei:'III'
                            ,piantan:'无'
                            ,fenqi:''
                            ,guanjie:'异常'
                            ,jizhang:'异常'
                            ,zhanli:'I'
                            ,fuzhu:'不需要'
                            ,butai:'正常步态'
                            ,buwei:'腰'
                            ,yuyan:'理解异常'
                            ,renzhi:'认知异常'
                            ,miaoshu:''
                            ,shou:''
                            ,xia:''
                        },
                    ]
                },

            ],
            tableShowList:[]
        }
    },
    methods:{
            handleClose(done){
                    this.$confirm('确认关闭？')
                .then(_ => {
                    done();
                })
                .catch(_ => {});
            },
            showDialog(data){
                this.dialogVisible = true
                // data 是对象
                this.tableShowList = data.dataList
            }
    }
}
</script>

<style>

</style>